version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run: pip install numpy
      - run: python demean_age.py
