version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - run:
          command: |
            . venv/bin/activate
            python demean_age.py
